using UnityEngine;

namespace Neo.UI.Menus
{
    /// <summary>
    /// Row + container prefabs a presenter instantiates when populating a menu at runtime (the CBN-style
    /// "default prefabs" path). Each row prefab holds a label, the control widget and a
    /// <see cref="MenuControlBinder"/>; the presenter clones it and calls <c>Configure</c>. Generated by
    /// the starter kit. Referenced from <c>NeoUISettings.menuWidgets</c> or assigned per presenter.
    /// </summary>
    [CreateAssetMenu(menuName = "Neo/UI/Menus/Widget Library", fileName = "MenuWidgetLibrary")]
    public class MenuWidgetLibrary : ScriptableObject
    {
        [Header("Control rows (label + control + binder)")]
        public GameObject toggleRow;
        public GameObject switchRow;
        public GameObject sliderRow;
        public GameObject stepperRow;
        public GameObject dropdownRow;
        public GameObject buttonRow;
        public GameObject labelRow;
        public GameObject keyRebindRow;

        [Header("Navigation")]
        [Tooltip("A UITab + UIPanel pair used to build category tabs (optional).")]
        public GameObject categoryTab;
        public GameObject categoryPanel;

        public GameObject RowFor(MenuControlKind kind)
        {
            switch (kind)
            {
                case MenuControlKind.Toggle: return toggleRow;
                case MenuControlKind.Switch: return switchRow != null ? switchRow : toggleRow;
                case MenuControlKind.Slider: return sliderRow;
                case MenuControlKind.Stepper: return stepperRow;
                case MenuControlKind.Dropdown: return dropdownRow;
                case MenuControlKind.Button: return buttonRow;
                case MenuControlKind.KeyRebind: return keyRebindRow != null ? keyRebindRow : buttonRow;
                default: return labelRow;
            }
        }
    }
}
