using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AlterEyes.UI.Menus;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

namespace AlterEyes.UI.Editor
{
    /// <summary> Result of a generator run: what was created/updated, plus collisions and issues. </summary>
    public class GenerateReport
    {
        public readonly List<string> created = new List<string>();
        public readonly List<string> updated = new List<string>();
        public readonly List<string> collisions = new List<string>();
        public readonly List<string> issues = new List<string>();

        public bool hasProblems => collisions.Count > 0 || issues.Count > 0;

        public override string ToString()
        {
            var lines = new List<string>();
            lines.AddRange(created.Select(c => $"[created] {c}"));
            lines.AddRange(updated.Select(u => $"[updated] {u}"));
            lines.AddRange(collisions.Select(c => $"[COLLISION] {c}"));
            lines.AddRange(issues.Select(i => $"[ISSUE] {i}"));
            return lines.Count == 0 ? "Nothing to do." : string.Join("\n", lines);
        }
    }

    /// <summary>
    /// Consumes a UI spec and produces real Unity assets: theme tokens, animation presets,
    /// view prefabs, ID database entries and the flow graph. Idempotent: generated assets
    /// (carrying <see cref="GeneratedMarker"/> / the generated flag) are updated in place;
    /// hand-made assets at generated paths are reported as collisions and left untouched.
    /// </summary>
    public static class UISpecGenerator
    {
        public const string GeneratedRoot = "Assets/AEUI Generated";
        public const string GeneratedFlowTag = "[generated by AlterEyes.UI spec — edits via spec or graph window]";

        // catalogs generated this run, so the view-embedded "settings"/"cheats" elements can find them
        private static readonly Dictionary<string, MenuCatalog> s_catalogs =
            new Dictionary<string, MenuCatalog>(StringComparer.Ordinal);
        private static readonly Dictionary<string, InputActionAsset> s_catalogInputAssets =
            new Dictionary<string, InputActionAsset>(StringComparer.Ordinal);

        [MenuItem("Tools/AlterEyes UI/Generate From Spec…", priority = 1)]
        public static void GenerateFromSpecFileDialog()
        {
            string path = EditorUtility.OpenFilePanel("Select UI spec (JSON)", Application.dataPath, "json");
            if (string.IsNullOrEmpty(path)) return;
            GenerateReport report = GenerateFromSpecFile(path);
            Debug.Log($"[AlterEyes.UI] Spec generation finished:\n{report}");
            EditorUtility.DisplayDialog("Spec Generation", report.ToString(), "OK");
        }

        /// <summary> Batch-mode entry point: -executeMethod with -specPath &lt;file&gt;. </summary>
        public static GenerateReport GenerateFromSpecFile(string path)
        {
            string json = File.ReadAllText(path);
            return Generate(UISpec.FromJson(json));
        }

        /// <summary>
        /// CLI entry point: <c>-executeMethod AlterEyes.UI.Editor.UISpecGenerator.GenerateFromCommandLine
        /// -specPath &lt;file&gt;</c>. Exits 1 on generation issues/collisions, 0 otherwise.
        /// </summary>
        public static void GenerateFromCommandLine()
        {
            string path = null;
            string[] args = System.Environment.GetCommandLineArgs();
            for (int i = 0; i < args.Length - 1; i++)
                if (args[i] == "-specPath") path = args[i + 1];
            if (string.IsNullOrEmpty(path))
            {
                Console.WriteLine("[GENERATE] missing -specPath");
                EditorApplication.Exit(1);
                return;
            }
            GenerateReport report = GenerateFromSpecFile(path);
            Console.WriteLine($"[GENERATE]\n{report}");
            EditorApplication.Exit(report.hasProblems ? 1 : 0);
        }

        public static GenerateReport Generate(UISpec spec)
        {
            var report = new GenerateReport();
            AEUISettings settings = AEUISettingsBootstrap.GetOrCreateSettings();

            try
            {
                // self-heal: deleted generated popups (test cleanups, manual deletes) leave
                // dangling database links behind — drop them loudly before regenerating
                if (settings.popupDatabase != null)
                {
                    foreach (string pruned in settings.popupDatabase.PruneDanglingLinks())
                        report.updated.Add($"Pruned dangling popup link '{pruned}' (prefab deleted)");
                    EditorUtility.SetDirty(settings.popupDatabase);
                }

                if (spec.theme != null) GenerateTheme(spec.theme, settings, report);
                foreach (PresetSpec preset in spec.presets) GeneratePreset(preset, settings, report);

                // catalogs first — views may embed them via "settings"/"cheats" elements
                s_catalogs.Clear();
                s_catalogInputAssets.Clear();
                foreach (MenuCatalogSpec catalog in spec.settings) GenerateMenuCatalog(catalog, settings, report);
                foreach (MenuCatalogSpec catalog in spec.cheats) GenerateMenuCatalog(catalog, settings, report);

                if (spec.views.Count > 0 || spec.popups.Count > 0)
                {
                    // after spec tokens/styles, fills gaps only
                    StarterKitBootstrap.EnsureFactoryTokens(settings.theme);
                    StarterKitBootstrap.EnsureTextStyles(settings.theme);
                }
                foreach (ViewSpec view in spec.views) GenerateView(view, settings, report);
                foreach (PopupSpec popup in spec.popups) GeneratePopup(popup, settings, report);
                if (spec.flow != null) GenerateFlow(spec.flow, report);
            }
            catch (Exception e)
            {
                report.issues.Add($"Generation aborted: {e.Message}");
                Debug.LogException(e);
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            return report;
        }

        // ------------------------------------------------------------------ theme

        private static void GenerateTheme(ThemeSpec themeSpec, AEUISettings settings, GenerateReport report)
        {
            Theme theme = settings.theme;

            // bundle first — explicit spec tokens/variants override it below
            if (!string.IsNullOrEmpty(themeSpec.bundle))
            {
                if (ThemeBundles.TryGet(themeSpec.bundle, out ThemeBundles.Bundle bundle))
                    ThemeBundles.Apply(bundle, settings, report);
                else
                    report.issues.Add($"Unknown theme bundle '{themeSpec.bundle}' " +
                                      $"(available: {string.Join(", ", ThemeBundles.Names)})");
            }

            foreach (KeyValuePair<string, string> token in themeSpec.tokens)
            {
                if (!ColorUtils.TryParseHex(token.Value, out Color color))
                {
                    report.issues.Add($"Theme token '{token.Key}' has invalid color '{token.Value}'");
                    continue;
                }
                theme.SetToken(token.Key, color);
            }

            foreach (KeyValuePair<string, Dictionary<string, string>> variant in themeSpec.variants)
            {
                theme.AddVariant(variant.Key);
                foreach (KeyValuePair<string, string> token in variant.Value)
                {
                    if (!ColorUtils.TryParseHex(token.Value, out Color color))
                    {
                        report.issues.Add($"Variant '{variant.Key}' token '{token.Key}' has invalid color '{token.Value}'");
                        continue;
                    }
                    theme.SetToken(token.Key, color, variant.Key);
                }
            }

            EditorUtility.SetDirty(theme);
            report.updated.Add($"Theme '{theme.name}' ({themeSpec.tokens.Count} tokens, {themeSpec.variants.Count} extra variants)");
        }

        // ------------------------------------------------------------------ presets

        private static void GeneratePreset(PresetSpec presetSpec, AEUISettings settings, GenerateReport report)
        {
            EnsureFolder($"{GeneratedRoot}/Presets");
            string path = $"{GeneratedRoot}/Presets/{Sanitize(presetSpec.name)}.asset";

            var preset = AssetDatabase.LoadAssetAtPath<UIAnimationPreset>(path);
            bool created = preset == null;
            if (created) preset = ScriptableObject.CreateInstance<UIAnimationPreset>();

            preset.presetName = presetSpec.name;
            preset.category = presetSpec.type;
            ApplyPresetToAnimation(presetSpec, preset.animation, report);

            // configure BEFORE CreateAsset: the create-import serializes (and can reload) the
            // object, so fields assigned after it are lost on first run
            if (created) AssetDatabase.CreateAsset(preset, path);

            settings.animationPresets.AddOrUpdate(preset);
            EditorUtility.SetDirty(preset);
            EditorUtility.SetDirty(settings.animationPresets);
            (created ? report.created : report.updated).Add($"Animation preset '{presetSpec.name}' → {path}");
        }

        public static void ApplyPresetToAnimation(PresetSpec presetSpec, UIAnimation animation, GenerateReport report)
        {
            animation.purpose = ParseEnum(presetSpec.type, AnimationPurpose.Custom, report, "preset type");
            Ease defaultEase = ParseEnum(presetSpec.ease, Ease.OutCubic, report, "preset ease");

            animation.move.enabled = presetSpec.move != null && presetSpec.move.enabled;
            animation.rotate.enabled = presetSpec.rotate != null && presetSpec.rotate.enabled;
            animation.scale.enabled = presetSpec.scale != null && presetSpec.scale.enabled;
            animation.fade.enabled = presetSpec.fade != null && presetSpec.fade.enabled;

            if (animation.move.enabled)
            {
                ConfigureChannelSettings(animation.move.settings, presetSpec.move, presetSpec.duration, defaultEase, report);
                animation.move.fromDirection = ParseDirection(presetSpec.move.from, report);
                animation.move.toDirection = ParseDirection(presetSpec.move.to, report);
                animation.move.fromReference = ReferenceValue.StartValue;
                animation.move.toReference = ReferenceValue.StartValue;
            }

            if (animation.rotate.enabled)
            {
                ConfigureChannelSettings(animation.rotate.settings, presetSpec.rotate, presetSpec.duration, defaultEase, report);
                animation.rotate.fromReference = ReferenceValue.CustomValue;
                animation.rotate.toReference = ReferenceValue.CustomValue;
                animation.rotate.fromCustomValue = ParseVector3(presetSpec.rotate.from, Vector3.zero);
                animation.rotate.toCustomValue = ParseVector3(presetSpec.rotate.to, Vector3.zero);
            }

            if (animation.scale.enabled)
            {
                ConfigureChannelSettings(animation.scale.settings, presetSpec.scale, presetSpec.duration, defaultEase, report);
                animation.scale.fromReference = ReferenceValue.CustomValue;
                animation.scale.toReference = ReferenceValue.CustomValue;
                animation.scale.fromCustomValue = ParseScale(presetSpec.scale.from, Vector3.one);
                animation.scale.toCustomValue = ParseScale(presetSpec.scale.to, Vector3.one);
            }

            if (animation.fade.enabled)
            {
                ConfigureChannelSettings(animation.fade.settings, presetSpec.fade, presetSpec.duration, defaultEase, report);
                animation.fade.fromReference = ReferenceValue.CustomValue;
                animation.fade.toReference = ReferenceValue.CustomValue;
                animation.fade.fromCustomValue = ParseFloat(presetSpec.fade.from, animation.purpose == AnimationPurpose.Hide ? 1f : 0f);
                animation.fade.toCustomValue = ParseFloat(presetSpec.fade.to, animation.purpose == AnimationPurpose.Hide ? 0f : 1f);
            }
        }

        private static void ConfigureChannelSettings(TweenSettings settings, PresetChannelSpec channel,
            float defaultDuration, Ease defaultEase, GenerateReport report)
        {
            settings.duration = channel.duration ?? defaultDuration;
            settings.ease = string.IsNullOrEmpty(channel.ease)
                ? defaultEase
                : ParseEnum(channel.ease, defaultEase, report, "channel ease");
        }

        // ------------------------------------------------------------------ views

        private static void GenerateView(ViewSpec viewSpec, AEUISettings settings, GenerateReport report)
        {
            EnsureFolder($"{GeneratedRoot}/Views");
            string assetName = Sanitize($"{viewSpec.category}_{viewSpec.viewName}");
            string path = $"{GeneratedRoot}/Views/{assetName}.prefab";

            GameObject existing = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            bool created = existing == null;
            if (!created && existing.GetComponent<GeneratedMarker>() == null)
            {
                report.collisions.Add($"'{path}' exists but was not generated — view '{viewSpec.id}' skipped");
                return;
            }

            GameObject root = BuildViewGameObject(viewSpec, settings, report);
            PrefabUtility.SaveAsPrefabAsset(root, path);
            UnityEngine.Object.DestroyImmediate(root);

            settings.viewIds.Add(viewSpec.category, viewSpec.viewName);
            EditorUtility.SetDirty(settings.viewIds);
            (created ? report.created : report.updated).Add($"View '{viewSpec.id}' → {path}");
        }

        internal static GameObject BuildViewGameObject(ViewSpec viewSpec, AEUISettings settings, GenerateReport report)
        {
            var root = new GameObject(Sanitize($"{viewSpec.category}_{viewSpec.viewName}"), typeof(RectTransform), typeof(CanvasGroup));
            var rootRect = (RectTransform)root.transform;
            Stretch(rootRect);

            GeneratedMarker marker = root.AddComponent<GeneratedMarker>();
            marker.specSource = $"view:{viewSpec.id}";

            UIView view = root.AddComponent<UIView>();
            view.id = new ViewId(viewSpec.category, viewSpec.viewName);
            view.onStartBehaviour = ContainerStartBehaviour.InstantHide;
            // scene canvas sibling order is arbitrary (asset GUID order) — a node layering several
            // views (cheat sheet over the menu) needs each shown view to surface above its siblings
            view.bringToFrontOnShow = true;

            UIContainerUIAnimator animator = root.AddComponent<UIContainerUIAnimator>();
            animator.controller = view;
            ApplyPresetByName(viewSpec.showAnimation, animator.showAnimation, settings, report, $"view '{viewSpec.id}' showAnimation");
            ApplyPresetByName(viewSpec.hideAnimation, animator.hideAnimation, settings, report, $"view '{viewSpec.id}' hideAnimation");

            if (!string.IsNullOrEmpty(viewSpec.background))
            {
                GameObject background = CreateChild(rootRect, "Background", out RectTransform backgroundRect);
                Stretch(backgroundRect);
                background.AddComponent<Image>();
                AddThemeTarget(background, viewSpec.background);
            }

            var build = new ViewBuild { root = root };
            for (int i = 0; i < viewSpec.elements.Count; i++)
                BuildElement(viewSpec.elements[i], i, rootRect, settings, report, build);
            ResolveTabPanels(build, settings, report);

            return root;
        }

        /// <summary>
        /// Per-view scratch state collected while building elements so the tab↔panel links can be
        /// resolved after every sibling exists (a tab's "controls" panel may be declared after it).
        /// </summary>
        private sealed class ViewBuild
        {
            public GameObject root;
            public readonly List<(UITab tab, string controls)> tabPanelLinks = new List<(UITab, string)>();
            public readonly Dictionary<string, UIPanel> panels = new Dictionary<string, UIPanel>();
            private readonly Dictionary<string, UIToggleGroup> _toggleGroups = new Dictionary<string, UIToggleGroup>();

            /// <summary> Shared exclusivity group for standalone tabs declaring the same "group"
            /// name — lives on the view root so sibling order and nesting stay irrelevant. </summary>
            public UIToggleGroup GetOrCreateToggleGroup(string groupName, string category)
            {
                if (_toggleGroups.TryGetValue(groupName, out UIToggleGroup existing)) return existing;
                var created = root.AddComponent<UIToggleGroup>();
                created.id = new ToggleId(category ?? "Tabs", groupName);
                created.controlMode = UIToggleGroup.ControlMode.OneToggleOnEnforced;
                _toggleGroups[groupName] = created;
                return created;
            }
            /// <summary> Graphics of "image" elements / UIButtons, in build (= hierarchy) order —
            /// rich popups copy these into the UIPopup indexed slots. </summary>
            public readonly List<Graphic> imageSlots = new List<Graphic>();
            public readonly List<UIButton> buttonSlots = new List<UIButton>();
        }

        private static void BuildElement(ElementSpec element, int index, RectTransform parent,
            AEUISettings settings, GenerateReport report, ViewBuild build)
        {
            BuildElementTree(element, index, parent, settings, report, inLayout: false, build: build);
        }

        /// <summary>
        /// Wires each tab's "controls" to its sibling <see cref="UIPanel"/> (a direct in-prefab
        /// reference) and bakes WYSIWYG start visibility: the selected tab's panel shows, the rest
        /// hide. Matches the panel id exactly, then forgivingly by name; an unmatched "controls" is
        /// reported, never silently dropped.
        /// </summary>
        private static void ResolveTabPanels(ViewBuild build, AEUISettings settings, GenerateReport report)
        {
            foreach ((UITab tab, string controls) in build.tabPanelLinks)
            {
                if (tab == null) continue;
                UIPanel panel = MatchPanel(build, controls, report);
                if (panel == null)
                {
                    report.issues.Add($"Tab '{tab.id}' controls '{controls}' but no such panel exists in the view");
                    continue;
                }

                var so = new SerializedObject(tab);
                so.FindProperty("containerReference").objectReferenceValue = panel;
                so.ApplyModifiedPropertiesWithoutUndo();

                // WYSIWYG: the baked prefab equals the runtime start state. The panel hides by
                // deactivating its GameObject (disableGameObjectWhenHidden), so bake the selected
                // tab's panel active and the rest inactive — the controlling tab re-establishes the
                // same state at runtime (UITab pushes its selection to the container on enable).
                panel.gameObject.SetActive(tab.isOn);
            }
        }

        private static UIPanel MatchPanel(ViewBuild build, string controls, GenerateReport report)
        {
            CategoryNameId.Parse(controls, out string category, out string name);
            if (build.panels.TryGetValue($"{category}/{name}", out UIPanel exact)) return exact;

            // forgiving fallback: a bare "controls" name matches a panel of any category
            var byName = build.panels.Values.Where(p => p.id.Name == name).ToList();
            if (byName.Count == 1) return byName[0];
            if (byName.Count > 1)
                report.issues.Add($"Tab controls '{controls}' is ambiguous — {byName.Count} panels share the name '{name}'");
            return null;
        }

        /// <summary>
        /// Builds one element (and, for containers, its children) through UIWidgetFactory.
        /// inLayout: the parent is a layout group — sizes go through LayoutElement and the
        /// anchor/position overrides are skipped (the group owns placement).
        /// </summary>
        private static GameObject BuildElementTree(ElementSpec element, int index, RectTransform parent,
            AEUISettings settings, GenerateReport report, bool inLayout, ViewBuild build)
        {
            string category = null, name = null;
            if (!string.IsNullOrEmpty(element.id)) CategoryNameId.Parse(element.id, out category, out name);

            GameObject go = null;
            RectTransform childHost = null;     // where container children land
            bool childrenInLayout = true;       // safe areas host free-anchored children, not stacked ones

            switch (element.kind)
            {
                case "button":
                {
                    ValidateIcon(element, report);
                    go = UIWidgetFactory.CreateButton(parent, category, name, element.label,
                        element.icon, element.variant, element.sizeVariant);
                    UIButton button = go.GetComponent<UIButton>();
                    UIActionBehaviour click = button.GetOrAddBehaviour(BehaviourTrigger.Click);
                    if (element.onClickSignal != null)
                    {
                        click.sendSignal = true;
                        click.signalStream = new StreamId(element.onClickSignal.category, element.onClickSignal.name);
                        RegisterId(settings.streamIds, element.onClickSignal.category, element.onClickSignal.name);
                    }
                    AddViewCommand(go, element.onClickShowView, ViewCommandOnClick.Command.Show);
                    AddViewCommand(go, element.onClickHideView, ViewCommandOnClick.Command.Hide);
                    if (!string.IsNullOrEmpty(element.onClickPopup))
                        go.AddComponent<ShowPopupOnClick>().popupName = element.onClickPopup;
                    if (element.onClickClose)
                        go.AddComponent<HideContainerOnClick>();
                    build.buttonSlots.Add(button);
                    if (!string.IsNullOrEmpty(element.labelColor))
                    {
                        Transform label = go.transform.Find(UIWidgetFactory.LabelName);
                        ThemeColorTarget labelTarget = label != null ? label.GetComponent<ThemeColorTarget>() : null;
                        if (labelTarget != null) labelTarget.token = element.labelColor;
                    }
                    UIWidgetFactory.SetLabelTextStyle(go, element.textStyle);
                    if (element.badge.HasValue) UIWidgetFactory.CreateBadge(go, (int)element.badge.Value);
                    RegisterId(settings.buttonIds, category, name);
                    break;
                }
                case "toggle":
                    go = UIWidgetFactory.CreateToggle(parent, category, name, element.label);
                    UIWidgetFactory.SetLabelTextStyle(go, element.textStyle);
                    if ((element.value ?? 0f) >= 0.5f) UIWidgetFactory.BakeToggleOn(go);
                    if (!string.IsNullOrEmpty(element.group))
                        go.GetComponent<UIToggle>().toggleGroup =
                            build.GetOrCreateToggleGroup(element.group, category);
                    RegisterId(settings.toggleIds, category, name);
                    break;
                case "switch":
                    go = UIWidgetFactory.CreateSwitch(parent, category, name);
                    if ((element.value ?? 0f) >= 0.5f) UIWidgetFactory.BakeToggleOn(go);
                    RegisterId(settings.toggleIds, category, name);
                    break;
                case "tab":
                    // standalone tab (outside a tabbar) behaves like a toggle button; tabs naming
                    // the same "group" share one view-level UIToggleGroup for exclusivity
                    ValidateIcon(element, report);
                    go = UIWidgetFactory.CreateTab(parent, category, name, element.label,
                        group: string.IsNullOrEmpty(element.group)
                            ? null
                            : build.GetOrCreateToggleGroup(element.group, category),
                        icon: element.icon, variant: element.variant);
                    // sidebar-style tab lists bake their selected entry (tabbars bake the first)
                    if ((element.value ?? 0f) >= 0.5f) UIWidgetFactory.BakeToggleOn(go);
                    UIWidgetFactory.SetLabelTextStyle(go, element.textStyle);
                    if (element.badge.HasValue) UIWidgetFactory.CreateBadge(go, (int)element.badge.Value);
                    RegisterId(settings.toggleIds, category, name);
                    if (!string.IsNullOrEmpty(element.controls))
                        build.tabPanelLinks.Add((go.GetComponent<UITab>(), element.controls));
                    break;
                case "slider":
                    go = UIWidgetFactory.CreateSlider(parent, category, name,
                        element.min ?? 0f, element.max ?? 1f, element.value ?? 0.5f);
                    RegisterId(settings.sliderIds, category, name);
                    break;
                case "progress":
                    go = element.style == "radial"
                        ? UIWidgetFactory.CreateRadialProgress(parent, element.min ?? 0f, element.max ?? 1f,
                            element.value)
                        : UIWidgetFactory.CreateProgressBar(parent, element.min ?? 0f, element.max ?? 1f,
                            element.value);
                    break;
                case "tabbar":
                {
                    var tabs = new List<(string, string, string)>();
                    foreach (ElementSpec child in element.children)
                    {
                        ValidateIcon(child, report);
                        string tabCategory = category ?? "Tabs", tabName = null;
                        if (!string.IsNullOrEmpty(child.id)) CategoryNameId.Parse(child.id, out tabCategory, out tabName);
                        tabs.Add((tabName ?? child.label, child.label, child.icon));
                        RegisterId(settings.toggleIds, tabCategory, tabName ?? child.label);
                    }
                    go = UIWidgetFactory.CreateTabBar(parent, category ?? "Tabs", tabs);
                    foreach (ElementSpec child in element.children)
                    {
                        string tabName = null;
                        if (!string.IsNullOrEmpty(child.id)) CategoryNameId.Parse(child.id, out _, out tabName);
                        Transform tab = go.transform.Find($"Tab_{tabName ?? child.label}");
                        if (tab == null) continue;
                        if (!string.IsNullOrEmpty(child.textStyle))
                            UIWidgetFactory.SetLabelTextStyle(tab.gameObject, child.textStyle);
                        if (!string.IsNullOrEmpty(child.controls))
                            build.tabPanelLinks.Add((tab.GetComponent<UITab>(), child.controls));
                    }
                    break;
                }
                case "list":
                case "scroll":
                {
                    go = UIWidgetFactory.CreateListView(parent);
                    // no explicit size = fill the stack's leftover space — a fixed height can't
                    // follow aspect-ratio changes (the exporter never writes scroll sizes)
                    if (element.size == null)
                        UIWidgetFactory.WithLayoutSize(go, -1f, -1f, flexibleHeight: 1f);
                    childHost = (RectTransform)go.transform
                        .Find(UIWidgetFactory.ViewportName).Find(UIWidgetFactory.ContentName);
                    if (element.spacing.HasValue)
                        childHost.GetComponent<VerticalLayoutGroup>().spacing = element.spacing.Value;
                    // "background": "none" = a transparent scroll region (full-bleed pages over a
                    // view gradient) — strip the card backing; the exporter writes "none" back
                    if (element.background == "none")
                    {
                        UnityEngine.Object.DestroyImmediate(go.GetComponent<ThemeShapeStyleTarget>());
                        UnityEngine.Object.DestroyImmediate(go.GetComponent<ThemeColorTarget>());
                        UnityEngine.Object.DestroyImmediate(go.GetComponent<AEShape>());
                    }
                    break;
                }
                case "vstack":
                case "hstack":
                    go = UIWidgetFactory.CreateStack(parent, element.kind == "vstack",
                        element.padding ?? 0f, element.spacing ?? 8f);
                    childHost = (RectTransform)go.transform;
                    if (element.cascade) go.AddComponent<UICascadeChildren>();
                    if (!string.IsNullOrEmpty(element.align))
                        go.GetComponent<HorizontalOrVerticalLayoutGroup>().childAlignment =
                            ParseStackAlignment(element.align);
                    break;
                case "grid":
                {
                    Vector2 cell = element.cellSize != null && element.cellSize.Length >= 2
                        ? new Vector2(element.cellSize[0], element.cellSize[1])
                        : new Vector2(120f, 120f);
                    go = UIWidgetFactory.CreateGrid(parent, element.padding ?? 0f,
                        element.spacing ?? 8f, element.columns ?? 0, cell);
                    // no explicit column count = responsive: fit as many cells as the width allows
                    if ((element.columns ?? 0) <= 0) go.AddComponent<UIResponsiveGridColumns>();
                    childHost = (RectTransform)go.transform;
                    if (element.cascade) go.AddComponent<UICascadeChildren>();
                    if (!string.IsNullOrEmpty(element.align))
                        go.GetComponent<GridLayoutGroup>().childAlignment = ParseStackAlignment(element.align);
                    break;
                }
                case "panel":
                {
                    string panelCategory = category ?? "Panels", panelName = name ?? $"Panel{index}";
                    go = UIWidgetFactory.CreatePanel(parent, panelCategory, panelName,
                        element.padding ?? 0f, element.spacing ?? 8f);
                    childHost = (RectTransform)go.transform;
                    if (element.cascade) go.AddComponent<UICascadeChildren>();
                    RegisterId(settings.panelIds, panelCategory, panelName);
                    UIPanel panel = go.GetComponent<UIPanel>();
                    string panelKey = panel.id.ToString();
                    if (build.panels.ContainsKey(panelKey))
                        report.issues.Add($"Duplicate panel id '{panelKey}' — tab 'controls' targeting it is ambiguous");
                    else
                        build.panels[panelKey] = panel;
                    break;
                }
                case "spacer":
                {
                    go = UIWidgetFactory.CreateRect(parent, "Spacer", new Vector2(8f, 8f));
                    var flexible = go.AddComponent<LayoutElement>();
                    // flex only along the parent stack's main axis: a both-ways flexible spacer
                    // inside an hstack reports flexibleHeight upward and the enclosing vstack dumps
                    // ALL leftover vertical space into that one row
                    bool inHorizontalStack = parent.GetComponent<HorizontalLayoutGroup>() != null;
                    bool inVerticalStack = parent.GetComponent<VerticalLayoutGroup>() != null;
                    flexible.flexibleWidth = inVerticalStack ? 0f : 1f;
                    flexible.flexibleHeight = inHorizontalStack ? 0f : 1f;
                    break;
                }
                case "input":
                    go = UIWidgetFactory.CreateInputField(parent, element.label);
                    break;
                case "stepper":
                    go = UIWidgetFactory.CreateStepper(parent, category, name,
                        element.min ?? 0f, element.max ?? 10f, element.value ?? 0f, element.step ?? 1f);
                    if (!string.IsNullOrEmpty(name))
                    {
                        // the plus/minus buttons carry derived ids — register them or validation flags them
                        RegisterId(settings.buttonIds, category, name + UIWidgetFactory.StepperButtonSuffixMinus);
                        RegisterId(settings.buttonIds, category, name + UIWidgetFactory.StepperButtonSuffixPlus);
                    }
                    break;
                case "safearea":
                    go = UIWidgetFactory.CreateSafeArea(parent);
                    childHost = (RectTransform)go.transform;
                    childrenInLayout = false; // plain container: children keep anchors/positions
                    break;
                case "overlay":
                    // z-stack: children keep their own anchors/positions and layer over the host
                    // (full-bleed art + corner badges + pinned labels in one card)
                    go = UIWidgetFactory.CreateRect(parent, "Overlay", new Vector2(320f, 320f));
                    go.AddComponent<UIOverlay>();
                    childHost = (RectTransform)go.transform;
                    childrenInLayout = false;
                    break;
                case "dropdown":
                    go = UIWidgetFactory.CreateDropdown(parent, category, name, element.options,
                        (int)(element.value ?? 0f));
                    RegisterId(settings.dropdownIds, category, name);
                    break;
                case "settings":
                case "cheats":
                    go = BuildMenuElement(element, parent, settings, report, build);
                    break;
                case "text":
                {
                    TextMeshProUGUI text = UIWidgetFactory.CreateLabel(parent, element.label,
                        element.labelColor, element.fontSize ?? 32f, name: "Text",
                        alignment: ParseAlignment(element.align), textStyle: element.textStyle);
                    if (!string.IsNullOrEmpty(element.outlineColor) || element.outlineWidth.HasValue)
                        UIWidgetFactory.ApplyTextOutline(text,
                            ParseColorRef(element.outlineColor, report).Resolve(),
                            element.outlineWidth ?? 0.25f);
                    go = text.gameObject;
                    var rect = (RectTransform)go.transform;
                    rect.anchorMin = rect.anchorMax = rect.pivot = new Vector2(0.5f, 0.5f);
                    rect.sizeDelta = new Vector2(320f, 80f);
                    break;
                }
                case "counter":
                {
                    TextMeshProUGUI text = UIWidgetFactory.CreateCounter(parent, element.value ?? 0f,
                        element.label, element.labelColor ?? UIWidgetFactory.TokenTextStrong,
                        element.fontSize ?? 30f, element.textStyle);
                    go = text.gameObject;
                    var rect = (RectTransform)go.transform;
                    rect.anchorMin = rect.anchorMax = rect.pivot = new Vector2(0.5f, 0.5f);
                    rect.sizeDelta = new Vector2(320f, 80f);
                    break;
                }
                case "image":
                    go = UIWidgetFactory.CreateRect(parent, "Image", new Vector2(320f, 80f));
                    if (!string.IsNullOrEmpty(element.src))
                    {
                        // sprite art rides an AEShape texture fill so "radius" rounds the corners;
                        // the fill stays white (no token) unless the spec explicitly tints it
                        var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(element.src);
                        if (sprite == null)
                            report.issues.Add($"Image src '{element.src}' did not load as a Sprite");
                        AEShape imageShape = UIWidgetFactory.AddShape(go, ShapeType.RoundedRect,
                            element.radius ?? 0f,
                            fillToken: element.gradient == null ? element.background : null,
                            style: element.style);
                        imageShape.sprite = sprite;
                        if (element.fit == "cover")
                            imageShape.textureFitMode = ShapeTextureFit.Cover;
                    }
                    else
                    {
                        go.AddComponent<Image>();
                        if (!string.IsNullOrEmpty(element.background) && element.gradient == null)
                            UIWidgetFactory.AddColorToken(go, element.background);
                    }
                    build.imageSlots.Add(go.GetComponent<Graphic>());
                    break;
                case "shape":
                {
                    go = UIWidgetFactory.CreateRect(parent, "Shape", new Vector2(320f, 80f));
                    // a gradient owns Graphic.color (AEGradient multiplies onto it) — skip the fill token
                    string fillToken = element.gradient == null ? element.background : null;
                    AEShape aeShape = UIWidgetFactory.AddShape(go, ParseShapeType(element.shape, report),
                        element.radius ?? 12f, fillToken, element.style);
                    if (element.thickness.HasValue) aeShape.ringThickness = element.thickness.Value;
                    if (element.arcStart.HasValue) aeShape.arcStart = element.arcStart.Value;
                    if (element.arcSweep.HasValue) aeShape.arcSweep = element.arcSweep.Value;
                    break;
                }
                case "icon":
                {
                    if (string.IsNullOrEmpty(element.icon))
                        report.issues.Add("Icon element is missing its 'name'");
                    ValidateIcon(element, report);
                    float iconSize = element.size != null && element.size.Length >= 2
                        ? Mathf.Min(element.size[0], element.size[1])
                        : 32f;
                    TextMeshProUGUI iconText = UIWidgetFactory.CreateIcon(parent, element.icon, iconSize,
                        element.labelColor ?? UIWidgetFactory.TokenTextDefault);
                    go = iconText.gameObject;
                    break;
                }
                default:
                    report.issues.Add($"Unknown element kind '{element.kind}'");
                    return null;
            }

            string elementName = !string.IsNullOrEmpty(element.id)
                ? Sanitize(element.id.Replace('/', '_'))
                : $"{element.kind}_{index}";
            go.name = elementName;

            // a container with visual fields gets an AEShape on its layout host (card/sheet look) —
            // without this, "style"/"background" on a stack would silently render nothing
            if (IsPlainContainer(element.kind)
                && (!string.IsNullOrEmpty(element.background) || !string.IsNullOrEmpty(element.style)
                    || element.gradient != null || element.radius.HasValue))
                UIWidgetFactory.AddShape(go, ShapeType.RoundedRect, element.radius ?? 16f,
                    fillToken: element.gradient == null ? element.background : null,
                    style: element.style);

            ApplyCommonOverrides(element, go, index, inLayout);

            // theme-riding two-stop gradient on plain graphics (the gradient owns the color)
            if (element.gradient != null
                && (element.kind == "shape" || element.kind == "image" || IsPlainContainer(element.kind))
                && go.GetComponent<Graphic>() != null)
            {
                var gradient = go.AddComponent<AEGradient>();
                gradient.colorA = ParseColorRef(element.gradient.from, report);
                gradient.colorB = ParseColorRef(element.gradient.to, report);
                gradient.angle = element.gradient.angle;
            }

            // background token on widgets that don't take it in their factory call
            if (!string.IsNullOrEmpty(element.background) && element.gradient == null
                && go.GetComponent<ThemeColorTarget>() == null
                && go.GetComponent<Graphic>() != null)
                UIWidgetFactory.AddColorToken(go, element.background);

            // shape style override on any AEShape-rooted widget (progress owns "style" = radial)
            if (!string.IsNullOrEmpty(element.style) && element.kind != "shape" && element.kind != "progress"
                && go.GetComponent<AEShape>() != null
                && go.GetComponent<ThemeShapeStyleTarget>() == null)
            {
                var styleTarget = go.AddComponent<ThemeShapeStyleTarget>();
                styleTarget.style = element.style;
                styleTarget.applyFillColor = false;
            }
            if (element.radius.HasValue && element.kind != "shape" && go.TryGetComponent(out AEShape rootShape))
                rootShape.cornerRadius = element.radius.Value;

            // data-bound list/grid: build the row template once (kept inactive) and wire a binder;
            // rows are cloned from it at runtime per UIData row. The template is the only "child".
            if (childHost != null && element.item != null)
            {
                GameObject templateGo = BuildElementTree(element.item, 0, childHost, settings, report,
                    inLayout: childrenInLayout, build: build);
                if (templateGo != null)
                {
                    templateGo.name = "ItemTemplate";
                    templateGo.SetActive(false);
                    var binder = childHost.gameObject.AddComponent<UIBoundList>();
                    binder.template = templateGo;
                    if (!string.IsNullOrEmpty(element.bind))
                    {
                        CategoryNameId.Parse(element.bind, out string bindCategory, out string bindName);
                        binder.source = new CategoryNameId(bindCategory, bindName);
                        RegisterId(settings.streamIds, bindCategory, bindName);
                    }
                }
            }

            if (childHost != null)
                for (int i = 0; i < element.children.Count; i++)
                    BuildElementTree(element.children[i], i, childHost, settings, report,
                        inLayout: childrenInLayout, build: build);

            return go;
        }

        private static void ApplyCommonOverrides(ElementSpec element, GameObject go, int index, bool inLayout)
        {
            var rect = (RectTransform)go.transform;
            // z rotation is placement-independent (layout groups position the unrotated rect):
            // corner ribbons and slanted banners ride it in both layout and free contexts
            if (element.rotation.HasValue)
                rect.localRotation = Quaternion.Euler(0f, 0f, element.rotation.Value);
            if (inLayout)
            {
                // the layout group owns placement; explicit size rides a LayoutElement.
                // min = preferred: an authored size is rigid — when a page overflows, layout
                // groups squeeze children toward min, and min 0 crushes sized art/rows to nothing
                if (element.size != null && element.size.Length >= 2)
                {
                    var layoutElement = go.GetComponent<LayoutElement>();
                    if (layoutElement == null) layoutElement = go.AddComponent<LayoutElement>();
                    if (element.size[0] > 0f)
                    {
                        layoutElement.preferredWidth = element.size[0];
                        layoutElement.minWidth = element.size[0];
                    }
                    if (element.size[1] > 0f)
                    {
                        layoutElement.preferredHeight = element.size[1];
                        layoutElement.minHeight = element.size[1];
                    }
                    rect.sizeDelta = new Vector2(element.size[0], element.size[1]);
                }
                else if ((element.kind == "shape" || element.kind == "image")
                    && go.GetComponent<LayoutElement>() == null)
                {
                    // plain graphics report no preferred size — without this they collapse to 0
                    UIWidgetFactory.WithLayoutSize(go,
                        rect.sizeDelta.x > 0f ? rect.sizeDelta.x : -1f, rect.sizeDelta.y);
                }
                if (element.flex.HasValue && element.flex.Value > 0f)
                {
                    // flex rides the parent stack's main axis: leftover space is shared
                    // proportionally between flexible children, so bars genuinely fill any
                    // width instead of relying on authored pixel sizes
                    var flexElement = go.GetComponent<LayoutElement>();
                    if (flexElement == null) flexElement = go.AddComponent<LayoutElement>();
                    if (go.transform.parent != null
                        && go.transform.parent.GetComponent<HorizontalLayoutGroup>() != null)
                        flexElement.flexibleWidth = element.flex.Value;
                    else
                        flexElement.flexibleHeight = element.flex.Value;
                }
                return;
            }

            if (!string.IsNullOrEmpty(element.anchor)) UIWidgetFactory.TryApplyAnchor(rect, element.anchor);
            if (element.size != null && element.size.Length >= 2)
            {
                Vector2 current = rect.sizeDelta;
                rect.sizeDelta = new Vector2(
                    element.size[0] > 0f ? element.size[0] : current.x,
                    element.size[1] > 0f ? element.size[1] : current.y);
            }
            if (element.position != null && element.position.Length >= 2)
                rect.anchoredPosition = new Vector2(element.position[0], element.position[1]);
            else if (string.IsNullOrEmpty(element.anchor)
                     && Mathf.Approximately(rect.anchorMin.y, rect.anchorMax.y))
                // legacy auto-stack for anchor-less fixed-size rects so they don't pile up at
                // center — never for stretched rects (safearea, full-bleed children), which it
                // would shove off-screen by index
                rect.anchoredPosition = new Vector2(0f, -index * 96f);
        }

        private static TMPro.TextAlignmentOptions ParseAlignment(string align)
        {
            switch (align)
            {
                case "left": return TMPro.TextAlignmentOptions.Left;
                case "right": return TMPro.TextAlignmentOptions.Right;
                default: return TMPro.TextAlignmentOptions.Center;
            }
        }

        /// <summary> Container kinds that may carry card decor (an AEShape on the host). </summary>
        private static bool IsPlainContainer(string kind) =>
            kind == "vstack" || kind == "hstack" || kind == "grid" || kind == "panel" || kind == "overlay";

        /// <summary>
        /// "align" on a stack → childAlignment. Middle row so an hstack centers/right-packs its
        /// children and a vstack shorter than its container centers vertically.
        /// </summary>
        private static TextAnchor ParseStackAlignment(string align)
        {
            switch (align)
            {
                case "center": return TextAnchor.MiddleCenter;
                case "right": return TextAnchor.MiddleRight;
                default: return TextAnchor.MiddleLeft;
            }
        }

        /// <summary> "#hex" → literal color ref; anything else is a theme token name. </summary>
        private static ThemeColorRef ParseColorRef(string value, GenerateReport report)
        {
            if (string.IsNullOrEmpty(value)) return new ThemeColorRef(Color.white);
            if (value.StartsWith("#"))
            {
                if (ColorUtils.TryParseHex(value, out Color color)) return new ThemeColorRef(color);
                report.issues.Add($"Invalid gradient color '{value}'");
                return new ThemeColorRef(Color.white);
            }
            return new ThemeColorRef(value);
        }

        /// <summary> Unknown icon names become loud report issues (the factory still renders a fallback). </summary>
        private static void ValidateIcon(ElementSpec element, GenerateReport report)
        {
            if (string.IsNullOrEmpty(element.icon)) return;
            if (!IconMap.TryGetGlyph(element.icon, out _))
                report.issues.Add($"Element '{element.id ?? element.kind}': unknown icon '{element.icon}' (see IconMap for valid names)");
        }

        private static ShapeType ParseShapeType(string value, GenerateReport report)
        {
            if (string.IsNullOrEmpty(value)) return ShapeType.RoundedRect;
            if (Enum.TryParse(value, ignoreCase: true, out ShapeType parsed)) return parsed;
            report.issues.Add($"Unknown shape '{value}', using RoundedRect");
            return ShapeType.RoundedRect;
        }

        private static void RegisterId(IdDatabase database, string category, string name)
        {
            if (database == null || string.IsNullOrEmpty(category) || string.IsNullOrEmpty(name)) return;
            database.Add(category, name);
            EditorUtility.SetDirty(database);
        }

        // ------------------------------------------------------------------ menus (settings / cheats)

        private static void GenerateMenuCatalog(MenuCatalogSpec spec, AEUISettings settings, GenerateReport report)
        {
            EnsureFolder($"{GeneratedRoot}/Menus");
            bool isCheat = spec.kind == MenuCatalogSpec.CheatKind;
            string assetName = Sanitize($"{spec.category}_{spec.menuName}");
            string path = $"{GeneratedRoot}/Menus/{assetName}.asset";

            var existing = AssetDatabase.LoadAssetAtPath<MenuCatalog>(path);
            bool typeMismatch = existing != null && (isCheat ? !(existing is CheatCatalog) : !(existing is SettingsCatalog));
            bool created = existing == null || typeMismatch;
            MenuCatalog catalog;
            if (created)
            {
                if (typeMismatch) AssetDatabase.DeleteAsset(path);
                catalog = (MenuCatalog)ScriptableObject.CreateInstance(isCheat ? typeof(CheatCatalog) : typeof(SettingsCatalog));
            }
            else catalog = existing;

            catalog.category = spec.category;
            catalog.menuName = spec.menuName;
            catalog.groups = new List<string>(spec.groups);
            catalog.startGroup = spec.start;
            catalog.inputActionAssetPath = spec.inputActionAsset;
            if (catalog is CheatCatalog cheatCatalog) cheatCatalog.favouritesEnabled = spec.favourites;

            catalog.items.Clear();
            foreach (MenuItemSpec item in spec.items)
            {
                catalog.items.Add(ToDefinition(item));
                switch (MapKind(item.kind))
                {
                    case MenuControlKind.Dropdown: RegisterId(settings.dropdownIds, item.category, item.name); break;
                    case MenuControlKind.Slider: RegisterId(settings.sliderIds, item.category, item.name); break;
                    case MenuControlKind.Toggle:
                    case MenuControlKind.Switch: RegisterId(settings.toggleIds, item.category, item.name); break;
                    case MenuControlKind.Button: RegisterId(settings.buttonIds, item.category, item.name); break;
                }
            }

            if (created) AssetDatabase.CreateAsset(catalog, path);
            EditorUtility.SetDirty(catalog);

            s_catalogs[catalog.Id] = catalog;
            if (!string.IsNullOrEmpty(spec.inputActionAsset))
            {
                var asset = AssetDatabase.LoadAssetAtPath<InputActionAsset>(spec.inputActionAsset);
                if (asset == null)
                    report.issues.Add($"Catalog '{catalog.Id}': input action asset '{spec.inputActionAsset}' not found");
                else s_catalogInputAssets[catalog.Id] = asset;
            }

            (created ? report.created : report.updated).Add(
                $"{(isCheat ? "Cheat" : "Settings")} catalog '{catalog.Id}' ({catalog.items.Count} items) → {path}");
        }

        private static MenuItemDefinition ToDefinition(MenuItemSpec item) => new MenuItemDefinition
        {
            category = item.category,
            name = item.name,
            kind = MapKind(item.kind),
            label = item.label,
            tooltip = item.tooltip,
            group = item.group,
            persisted = item.persisted,
            min = item.min ?? 0f,
            max = item.max ?? 1f,
            step = item.step ?? 1f,
            wholeNumbers = item.wholeNumbers,
            defaultValue = item.value,
            options = item.options != null ? new List<string>(item.options) : new List<string>(),
            emitOnDrag = item.emitOnDrag,
            emitOnRelease = item.emitOnRelease,
            inputAction = item.inputAction,
            bindingIndex = item.bindingIndex
        };

        private static MenuControlKind MapKind(string kind)
        {
            switch (kind)
            {
                case "button": return MenuControlKind.Button;
                case "toggle": return MenuControlKind.Toggle;
                case "switch": return MenuControlKind.Switch;
                case "slider": return MenuControlKind.Slider;
                case "stepper": return MenuControlKind.Stepper;
                case "dropdown": return MenuControlKind.Dropdown;
                case "rebind": return MenuControlKind.KeyRebind;
                default: return MenuControlKind.Label;
            }
        }

        private static MenuCatalog LookupCatalog(string id)
        {
            if (string.IsNullOrEmpty(id)) return null;
            CategoryNameId.Parse(id, out string category, out string name);
            string key = $"{category}/{name}";
            if (s_catalogs.TryGetValue(key, out MenuCatalog catalog)) return catalog;
            string assetName = Sanitize($"{category}_{name}");
            return AssetDatabase.LoadAssetAtPath<MenuCatalog>($"{GeneratedRoot}/Menus/{assetName}.asset");
        }

        /// <summary>
        /// Builds a baked menu (tabbar + per-group panels, or a flat row stack) from a generated catalog,
        /// attaching a <see cref="MenuControlBinder"/> per control. A <see cref="MenuPresenter"/> on the
        /// root registers the catalog at runtime; the baked binders self-wire (no runtime rebuild).
        /// </summary>
        private static GameObject BuildMenuElement(ElementSpec element, RectTransform parent,
            AEUISettings settings, GenerateReport report, ViewBuild build)
        {
            MenuCatalog catalog = LookupCatalog(element.catalog);
            GameObject root = UIWidgetFactory.CreateStack(parent, vertical: true, padding: 0f, spacing: 8f);
            root.name = "Menu";

            if (catalog == null)
            {
                report.issues.Add($"Menu element references catalog '{element.catalog}' which was not generated");
                return root;
            }

            MenuPresenter presenter = catalog is CheatCatalog
                ? root.AddComponent<CheatMenu>()
                : root.AddComponent<SettingsMenu>();
            presenter.catalog = catalog;
            presenter.buildOnStart = false;
            presenter.contentRoot = (RectTransform)root.transform;

            InputActionAsset rebindAsset = s_catalogInputAssets.TryGetValue(catalog.Id, out InputActionAsset a) ? a : null;
            List<string> groups = catalog.groups != null
                ? catalog.groups.Where(g => !string.IsNullOrEmpty(g)).ToList() : new List<string>();

            if (groups.Count > 0)
            {
                var tabs = groups.Select(g => (g, g, (string)null)).ToList();
                GameObject tabBar = UIWidgetFactory.CreateTabBar((RectTransform)root.transform, catalog.category, tabs);
                foreach (string group in groups)
                {
                    Transform tab = tabBar.transform.Find($"Tab_{group}");
                    if (tab != null) build.tabPanelLinks.Add((tab.GetComponent<UITab>(), group));
                }
                foreach (string group in groups)
                {
                    GameObject panel = UIWidgetFactory.CreatePanel((RectTransform)root.transform, catalog.category, group, 12f, 8f);
                    panel.name = $"Panel_{group}";
                    UIPanel panelComponent = panel.GetComponent<UIPanel>();
                    string panelKey = panelComponent.id.ToString();
                    if (!build.panels.ContainsKey(panelKey)) build.panels[panelKey] = panelComponent;
                    RegisterId(settings.panelIds, catalog.category, group);
                    foreach (MenuItemDefinition def in catalog.ItemsInGroup(group))
                        BuildMenuRow(catalog, def, (RectTransform)panel.transform, rebindAsset, settings, report);
                }
            }
            else
            {
                foreach (MenuItemDefinition def in catalog.items)
                    BuildMenuRow(catalog, def, (RectTransform)root.transform, rebindAsset, settings, report);
            }
            return root;
        }

        private static void BuildMenuRow(MenuCatalog catalog, MenuItemDefinition def, RectTransform parent,
            InputActionAsset rebindAsset, AEUISettings settings, GenerateReport report)
        {
            switch (def.kind)
            {
                case MenuControlKind.Label:
                    UIWidgetFactory.CreateLabel(parent, def.label, UIWidgetFactory.TokenTextMuted, 20f,
                        name: "Header", alignment: TMPro.TextAlignmentOptions.MidlineLeft,
                        textStyle: UIWidgetFactory.TextStyleCaption);
                    return;
                case MenuControlKind.Button:
                {
                    GameObject button = UIWidgetFactory.CreateButton(parent, def.Category, def.Name, def.label,
                        variant: UIWidgetFactory.VariantSecondary);
                    AddBinder(button, catalog, def, null);
                    RegisterId(settings.buttonIds, def.Category, def.Name);
                    return;
                }
                case MenuControlKind.KeyRebind:
                {
                    GameObject rebindBtn = UIWidgetFactory.CreateButton(parent, def.Category, def.Name + "_Rebind",
                        "—", variant: UIWidgetFactory.VariantSecondary);
                    GameObject row = UIWidgetFactory.CreateMenuRow(parent, $"Row_{def.Name}", def.label, rebindBtn);
                    var rebind = row.AddComponent<UIRebindControl>();
                    rebind.Configure(catalog, def, rebindAsset);
                    rebind.rebindButton = rebindBtn.GetComponent<UIButton>();
                    rebind.bindingLabel = rebindBtn.transform.Find(UIWidgetFactory.LabelName)?.GetComponent<TMP_Text>();
                    rebind.labelTarget = row.transform.Find(UIWidgetFactory.LabelName)?.GetComponent<TMP_Text>();
                    RegisterId(settings.buttonIds, def.Category, def.Name + "_Rebind");
                    return;
                }
            }

            GameObject control;
            switch (def.kind)
            {
                case MenuControlKind.Toggle:
                    control = UIWidgetFactory.CreateToggle(parent, def.Category, def.Name, "");
                    if (ParseBool(def.defaultValue)) UIWidgetFactory.BakeToggleOn(control);
                    RegisterId(settings.toggleIds, def.Category, def.Name);
                    break;
                case MenuControlKind.Switch:
                    control = UIWidgetFactory.CreateSwitch(parent, def.Category, def.Name);
                    if (ParseBool(def.defaultValue)) UIWidgetFactory.BakeToggleOn(control);
                    RegisterId(settings.toggleIds, def.Category, def.Name);
                    break;
                case MenuControlKind.Slider:
                    control = UIWidgetFactory.CreateSlider(parent, def.Category, def.Name,
                        def.min, def.max, ParseFloat(def.defaultValue, def.min));
                    RegisterId(settings.sliderIds, def.Category, def.Name);
                    break;
                case MenuControlKind.Stepper:
                    control = UIWidgetFactory.CreateStepper(parent, def.Category, def.Name,
                        def.min, def.max, ParseFloat(def.defaultValue, def.min), def.step);
                    RegisterId(settings.buttonIds, def.Category, def.Name + UIWidgetFactory.StepperButtonSuffixMinus);
                    RegisterId(settings.buttonIds, def.Category, def.Name + UIWidgetFactory.StepperButtonSuffixPlus);
                    break;
                case MenuControlKind.Dropdown:
                    control = UIWidgetFactory.CreateDropdown(parent, def.Category, def.Name, def.options,
                        (int)ParseFloat(def.defaultValue, 0f));
                    RegisterId(settings.dropdownIds, def.Category, def.Name);
                    break;
                default:
                    return;
            }
            GameObject rowGo = UIWidgetFactory.CreateMenuRow(parent, $"Row_{def.Name}", def.label, control);
            AddBinder(control, catalog, def, rowGo.transform.Find(UIWidgetFactory.LabelName)?.GetComponent<TMP_Text>());
        }

        private static void AddBinder(GameObject control, MenuCatalog catalog, MenuItemDefinition def, TMP_Text label)
        {
            var binder = control.AddComponent<MenuControlBinder>();
            binder.Configure(catalog, def, label);
        }

        // ------------------------------------------------------------------ popups

        private static void GeneratePopup(PopupSpec popupSpec, AEUISettings settings, GenerateReport report)
        {
            EnsureFolder($"{GeneratedRoot}/Popups");
            string path = $"{GeneratedRoot}/Popups/{Sanitize(popupSpec.name)}.prefab";

            GameObject existing = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            bool created = existing == null;
            if (!created && existing.GetComponent<GeneratedMarker>() == null)
            {
                report.collisions.Add($"'{path}' exists but was not generated — popup '{popupSpec.name}' skipped");
                return;
            }

            GameObject root;
            if (popupSpec.elements.Count > 0)
            {
                root = BuildRichPopup(popupSpec, settings, report);
            }
            else
            {
                root = UIWidgetFactory.CreatePopup(popupSpec.name, popupSpec.title, popupSpec.message);
                if (popupSpec.size != null && popupSpec.size.Length >= 2)
                    root.GetComponent<UIPopup>().content.sizeDelta =
                        new Vector2(popupSpec.size[0], popupSpec.size[1]);
            }
            if (popupSpec.close) UIWidgetFactory.CreatePopupCloseButton(root, popupSpec.name);
            GeneratedMarker marker = root.AddComponent<GeneratedMarker>();
            marker.specSource = $"popup:{popupSpec.name}";

            GameObject prefab = PrefabUtility.SaveAsPrefabAsset(root, path);
            UnityEngine.Object.DestroyImmediate(root);

            if (settings.popupDatabase != null)
            {
                settings.popupDatabase.AddOrUpdate(popupSpec.name, prefab);
                EditorUtility.SetDirty(settings.popupDatabase);
            }
            (created ? report.created : report.updated).Add($"Popup '{popupSpec.name}' → {path}");
        }

        /// <summary>
        /// Popup with spec-authored content: optional Title/Message labels followed by the element
        /// tree, all stacked in the card content. The UIPopup indexed slots (labels/images/buttons)
        /// fill in build order so the Doozy-style runtime data APIs (SetTexts/SetSprites/SetEvents)
        /// address the generated content.
        /// </summary>
        private static GameObject BuildRichPopup(PopupSpec popupSpec, AEUISettings settings, GenerateReport report)
        {
            Vector2 cardSize = popupSpec.size != null && popupSpec.size.Length >= 2
                ? new Vector2(popupSpec.size[0], popupSpec.size[1])
                : UIWidgetFactory.PopupDefaultCardSize;
            GameObject root = UIWidgetFactory.CreatePopupShell(popupSpec.name, cardSize, out RectTransform content);
            UIPopup popup = root.GetComponent<UIPopup>();

            if (!string.IsNullOrEmpty(popupSpec.title))
                popup.labels.Add(UIWidgetFactory.CreateLabel(content, popupSpec.title,
                    UIWidgetFactory.TokenTextStrong, 28f, "Title", textStyle: UIWidgetFactory.TextStyleHeading));
            if (!string.IsNullOrEmpty(popupSpec.message))
                popup.labels.Add(UIWidgetFactory.CreateLabel(content, popupSpec.message,
                    UIWidgetFactory.TokenTextDefault, 22f, "Message", textStyle: UIWidgetFactory.TextStyleBody));

            var build = new ViewBuild { root = root };
            for (int i = 0; i < popupSpec.elements.Count; i++)
                BuildElementTree(popupSpec.elements[i], i, content, settings, report, inLayout: true, build: build);
            ResolveTabPanels(build, settings, report);

            popup.images.AddRange(build.imageSlots);
            popup.buttons.AddRange(build.buttonSlots);
            return root;
        }

        private static void AddViewCommand(GameObject go, string viewId, ViewCommandOnClick.Command command)
        {
            if (string.IsNullOrEmpty(viewId)) return;
            CategoryNameId.Parse(viewId, out string category, out string name);
            ViewCommandOnClick viewCommand = go.AddComponent<ViewCommandOnClick>();
            viewCommand.command = command;
            viewCommand.view = new ViewId(category, name);
        }

        private static void AddLabel(RectTransform parent, string label, string colorToken)
        {
            GameObject labelGo = CreateChild(parent, "Label", out RectTransform labelRect);
            Stretch(labelRect);
            TextMeshProUGUI text = labelGo.AddComponent<TextMeshProUGUI>();
            text.text = label ?? "";
            text.alignment = TextAlignmentOptions.Center;
            text.fontSize = 32f;
            if (!string.IsNullOrEmpty(colorToken)) AddThemeTarget(labelGo, colorToken);
        }

        private static void AddThemeTarget(GameObject go, string token)
        {
            ThemeColorTarget target = go.AddComponent<ThemeColorTarget>();
            target.token = token;
        }

        private static void ApplyPresetByName(string presetName, UIAnimation animation,
            AEUISettings settings, GenerateReport report, string context)
        {
            if (string.IsNullOrEmpty(presetName)) return;
            UIAnimationPreset preset = settings.animationPresets != null ? settings.animationPresets.Get(presetName) : null;
            if (preset == null)
            {
                report.issues.Add($"{context}: preset '{presetName}' not found (define it in the spec's presets section)");
                return;
            }
            preset.CopyTo(animation);
        }

        // ------------------------------------------------------------------ flow

        private static void GenerateFlow(FlowSpec flowSpec, GenerateReport report)
        {
            EnsureFolder($"{GeneratedRoot}/Flow");
            string path = $"{GeneratedRoot}/Flow/{Sanitize(flowSpec.name)}.asset";

            var graph = AssetDatabase.LoadAssetAtPath<FlowGraph>(path);
            bool created = graph == null;
            if (!created && (graph.graphDescription == null || !graph.graphDescription.Contains("[generated")))
            {
                report.collisions.Add($"'{path}' exists but was not generated — flow '{flowSpec.name}' skipped");
                return;
            }
            if (created) graph = ScriptableObject.CreateInstance<FlowGraph>();

            graph.graphName = flowSpec.name;
            graph.graphDescription = GeneratedFlowTag;
            graph.nodes.Clear();

            var start = graph.AddNode<StartNode>("Start", new Vector2(0f, 0f));
            if (!string.IsNullOrEmpty(flowSpec.start))
                start.outputs.Add(new FlowEdge { portName = "Start", toNode = flowSpec.start, allowsBack = false });

            for (int i = 0; i < flowSpec.nodes.Count; i++)
            {
                FlowNodeSpec nodeSpec = flowSpec.nodes[i];
                var node = graph.AddNode<UINode>(nodeSpec.name, new Vector2(280f * (i + 1), 120f * (i % 3)));
                node.hideShownViewsOnExit = true;
                foreach (string shownView in nodeSpec.views)
                {
                    CategoryNameId.Parse(shownView, out string category, out string name);
                    node.showViews.Add(new UINode.ViewRef(category, name));
                }
                foreach (string hiddenView in nodeSpec.hide)
                {
                    CategoryNameId.Parse(hiddenView, out string category, out string name);
                    node.hideViews.Add(new UINode.ViewRef(category, name));
                }
                foreach (FlowEdgeSpec edgeSpec in nodeSpec.next)
                {
                    node.outputs.Add(new FlowEdge
                    {
                        portName = edgeSpec.trigger != null ? edgeSpec.trigger.ToString() : "Next",
                        toNode = edgeSpec.to,
                        allowsBack = edgeSpec.allowsBack,
                        trigger = edgeSpec.trigger
                    });
                }
            }

            graph.startNode = "Start";
            List<string> graphIssues = graph.Validate();
            foreach (string issue in graphIssues) report.issues.Add($"Flow '{flowSpec.name}': {issue}");

            if (created) AssetDatabase.CreateAsset(graph, path);
            EditorUtility.SetDirty(graph);
            (created ? report.created : report.updated).Add($"Flow graph '{flowSpec.name}' → {path}");
        }

        // ------------------------------------------------------------------ helpers

        private static GameObject CreateChild(RectTransform parent, string name, out RectTransform rect)
        {
            var go = new GameObject(name, typeof(RectTransform));
            rect = (RectTransform)go.transform;
            rect.SetParent(parent, worldPositionStays: false);
            return go;
        }

        private static void Stretch(RectTransform rect)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;
        }

        private static T ParseEnum<T>(string value, T fallback, GenerateReport report, string context) where T : struct
        {
            if (string.IsNullOrEmpty(value)) return fallback;
            if (Enum.TryParse(value, ignoreCase: true, out T parsed)) return parsed;
            report.issues.Add($"Unknown {context} '{value}', using {fallback}");
            return fallback;
        }

        private static UIMoveDirection ParseDirection(string value, GenerateReport report)
        {
            if (string.IsNullOrEmpty(value)) return UIMoveDirection.CustomPosition;
            if (Enum.TryParse(value, ignoreCase: true, out UIMoveDirection direction)) return direction;
            report.issues.Add($"Unknown move direction '{value}', using CustomPosition");
            return UIMoveDirection.CustomPosition;
        }

        private static float ParseFloat(string value, float fallback) =>
            float.TryParse(value ?? "", System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out float f) ? f : fallback;

        private static bool ParseBool(string value) =>
            string.Equals(value, "True", StringComparison.OrdinalIgnoreCase) || value == "1";

        private static Vector3 ParseVector3(string value, Vector3 fallback)
        {
            if (string.IsNullOrEmpty(value)) return fallback;
            string[] parts = value.Split(',');
            if (parts.Length == 3
                && float.TryParse(parts[0], System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out float x)
                && float.TryParse(parts[1], System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out float y)
                && float.TryParse(parts[2], System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out float z))
                return new Vector3(x, y, z);
            return fallback;
        }

        private static Vector3 ParseScale(string value, Vector3 fallback)
        {
            if (string.IsNullOrEmpty(value)) return fallback;
            if (float.TryParse(value, System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out float uniform))
                return new Vector3(uniform, uniform, 1f);
            return ParseVector3(value, fallback);
        }

        private static string Sanitize(string value)
        {
            foreach (char invalid in Path.GetInvalidFileNameChars())
                value = value.Replace(invalid, '_');
            return value;
        }

        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            string parent = Path.GetDirectoryName(path)?.Replace('\\', '/');
            string leaf = Path.GetFileName(path);
            if (!string.IsNullOrEmpty(parent) && !AssetDatabase.IsValidFolder(parent)) EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, leaf);
        }
    }
}
