using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace Neo.UI.Editor.Authoring
{
    /// <summary>
    /// "Capture to Spec" for native authoring: takes a <see cref="UIView"/> a developer built/edited
    /// directly in a scene and folds it back into its showcase's JSON spec + baseline — the round-trip
    /// that keeps the spec the source of truth even when the editing happened in plain Unity.
    /// <para>
    /// It reuses the WHOLE existing safety layer rather than re-implementing any of it: the live view is
    /// materialized as a generated-style prefab in the showcase's <c>Generated/Views</c> folder, then
    /// <see cref="SpecBaseline.CaptureEdits"/> runs INSIDE <see cref="NeoWorkspace.Scoped"/> so the
    /// folder-scoped export + off-spec lint + baseline rewrite all operate on that one showcase root.
    /// Off-spec edits (raw colors below a widget root, deleted internals) therefore still refuse the
    /// capture (unless forced) exactly as they do for the agent <c>sync</c> path. The human-readable spec
    /// file is mirrored from the merged result so it stays authoritative.
    /// </para>
    /// </summary>
    public static class NeoCapture
    {
        /// <summary>
        /// Resolves which showcase a hand-built view belongs to, without prompting: first the view root's
        /// <see cref="GeneratedMarker.showcaseId"/> (authoritative, stamped on first capture), then the
        /// active scene path matched against a registered showcase's <see cref="Showcase.ScenePath"/>.
        /// Returns false when neither resolves — the caller (overlay) then prompts the user to pick or
        /// create one.
        /// </summary>
        public static bool TryResolveShowcase(UIView view, out Showcase showcase)
        {
            showcase = null;
            if (view == null) return false;

            var marker = view.GetComponent<GeneratedMarker>();
            if (marker != null && !string.IsNullOrEmpty(marker.showcaseId)
                && ShowcaseRegistry.TryGet(marker.showcaseId, out showcase))
                return true;

            string scenePath = view.gameObject.scene.path;
            if (!string.IsNullOrEmpty(scenePath))
            {
                showcase = ShowcaseRegistry.All.FirstOrDefault(s =>
                    string.Equals(s.ScenePath, scenePath, StringComparison.OrdinalIgnoreCase));
                if (showcase != null) return true;
            }
            return false;
        }

        /// <summary>
        /// Captures <paramref name="view"/> into <paramref name="showcase"/>'s spec + baseline. Returns the
        /// <see cref="SyncResult"/> from the standing protocol (refused on off-spec edits unless
        /// <paramref name="force"/>); on success the showcase's spec JSON is rewritten to the merged spec.
        /// </summary>
        public static SyncResult CaptureView(UIView view, Showcase showcase, bool force = false)
        {
            if (view == null) return Failed("No view to capture.");
            if (showcase == null) return Failed("No target showcase — pick or create one before capturing.");

            using (NeoWorkspace.Scoped(showcase))
            {
                // Stamp attribution onto the live view so the next capture resolves home with no prompt.
                var marker = view.GetComponent<GeneratedMarker>() ?? view.gameObject.AddComponent<GeneratedMarker>();
                marker.specSource = $"view:{view.id.Category}/{view.id.Name}";
                marker.showcaseId = showcase.id;

                string path = UISpecGenerator.ViewPrefabPath(view.id.Category, view.id.Name);
                GameObject existingPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (existingPrefab != null && existingPrefab.GetComponent<GeneratedMarker>() == null)
                    return Failed($"'{path}' exists but was not generated by Neo UI — rename your view or that " +
                                  "asset so capture doesn't clobber a hand-made prefab.");

                // Materialize the live view as the generated-style prefab the folder-scoped export reads.
                // SaveAsPrefabAsset (not …AndConnect): the scene instance stays a plain object — v1 capture
                // is a snapshot, not a live prefab link.
                EnsureAssetFolder(Path.GetDirectoryName(path).Replace('\\', '/'));
                PrefabUtility.SaveAsPrefabAsset(view.gameObject, path);
                AssetDatabase.Refresh();

                // The standing protocol: export the showcase root → off-spec gate → fold into baseline.
                SyncResult sr = SpecBaseline.CaptureEdits(force);

                // Mirror the merged spec to the human-readable spec file (the source of truth).
                if (sr != null && sr.ok && sr.merged != null && !string.IsNullOrEmpty(showcase.specPath))
                {
                    EnsureAssetFolder(Path.GetDirectoryName(showcase.specPath).Replace('\\', '/'));
                    File.WriteAllText(showcase.specPath, sr.merged.ToJson());
                    AssetDatabase.ImportAsset(showcase.specPath);
                }
                return sr;
            }
        }

        /// <summary>
        /// Creates a brand-new showcase (a <see cref="ShowcaseDefinition"/> asset + an empty spec file) so a
        /// view built from scratch has somewhere to be captured. The first <see cref="CaptureView"/> then
        /// establishes the baseline and fills the spec. Returns the registered <see cref="Showcase"/>.
        /// </summary>
        public static Showcase CreateShowcase(string id, string title, string category)
        {
            id = (id ?? "").Trim();
            if (string.IsNullOrEmpty(id)) throw new ArgumentException("Showcase id must be non-empty", nameof(id));
            if (ShowcaseRegistry.TryGet(id, out Showcase already)) return already;

            string folder = $"{ShowcaseRegistry.ShowcasesRoot}/{id}";
            string specPath = $"{ShowcaseRegistry.ShowcasesRoot}/Specs/{id}.json";
            EnsureAssetFolder(folder);
            EnsureAssetFolder($"{ShowcaseRegistry.ShowcasesRoot}/Specs");

            if (!File.Exists(specPath))
            {
                File.WriteAllText(specPath, new UISpec().ToJson());
                AssetDatabase.ImportAsset(specPath);
            }

            // specJson stays unset (a .json imports as a TextAsset, not the DefaultAsset slot); point the
            // definition at the spec file via the explicit path override instead.
            var def = ScriptableObject.CreateInstance<ShowcaseDefinition>();
            def.id = id;
            def.title = string.IsNullOrWhiteSpace(title) ? id : title;
            def.category = string.IsNullOrWhiteSpace(category) ? "Custom" : category;
            def.specPathOverride = specPath;
            AssetDatabase.CreateAsset(def, $"{folder}/{id}.asset");
            AssetDatabase.SaveAssets();

            ShowcaseRegistry.InvalidateDiscovery();
            return ShowcaseRegistry.TryGet(id, out Showcase created) ? created : def.ToShowcase();
        }

        // ---------------------------------------------------------------- helpers

        private static SyncResult Failed(string note)
        {
            Debug.LogWarning($"[Neo.UI] capture: {note}");
            return new SyncResult { ok = false, refused = true, note = note };
        }

        // Recursively create a project-relative asset folder (AssetDatabase.CreateFolder needs each level).
        private static void EnsureAssetFolder(string folder)
        {
            if (string.IsNullOrEmpty(folder) || AssetDatabase.IsValidFolder(folder)) return;
            string parent = Path.GetDirectoryName(folder).Replace('\\', '/');
            string leaf = Path.GetFileName(folder);
            EnsureAssetFolder(parent);
            AssetDatabase.CreateFolder(parent, leaf);
        }
    }
}
