using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Neo.UI.Editor
{
    /// <summary>
    /// Emits a <c>// &lt;auto-generated&gt;</c> partial-class C# stub from a <see cref="BindingManifest"/>:
    /// greppable <c>const</c> ids for every view/signal/data source/setting, a <c>Wire()</c> that subscribes
    /// each domain signal and binds each setting (calling empty <c>partial void</c> hooks the developer fills
    /// in), and a <c>Populate…</c> helper per data source. Plan 3, deliverable A.
    ///
    /// The stub is written OUTSIDE <see cref="UISpecGenerator.GeneratedRoot"/> (default
    /// <see cref="DefaultDirectory"/>) so a spec regen of UI assets never wipes it, and it is regenerated
    /// idempotently (same manifest → byte-identical file). The developer's implementations live in a SIBLING
    /// partial (e.g. <c>{Class}.Handlers.cs</c>) that the generator never touches.
    /// </summary>
    public static class BindingStubGenerator
    {
        /// <summary> Where stubs land by default — game code, not generated UI assets. </summary>
        public const string DefaultDirectory = "Assets/Scripts/Generated";

        /// <summary> Namespace the generated partial and the developer's sibling partial share. </summary>
        public const string DefaultNamespace = "Game.UI";

        public static string ClassName(BindingManifest manifest)
        {
            string baseName = Ident(manifest?.flowName);
            if (baseName.Length == 0) baseName = "Game";
            // strip a trailing "UI" so flow "GameUI" → class "GameUIBindings", not "GameUIUIBindings"
            if (baseName.Length > 2 && baseName.EndsWith("UI", System.StringComparison.OrdinalIgnoreCase))
                baseName = baseName.Substring(0, baseName.Length - 2);
            return baseName + "UIBindings";
        }

        public static string DefaultPath(BindingManifest manifest) =>
            $"{DefaultDirectory}/{ClassName(manifest)}.g.cs";

        [MenuItem("Tools/Neo UI/Advanced/Generate Binding Stub", priority = 16)]
        public static void GenerateBindingStubMenu()
        {
            // derive from the live project (the prefabs materialize the spec); the spec stays the truth
            BindingManifest manifest = BindingManifest.Derive(UISpecExporter.ExportProject());
            string stub = Write(manifest, null);
            string manifestPath = $"{DefaultDirectory}/{ClassName(manifest)}.bindings.json";
            File.WriteAllText(manifestPath, manifest.ToJson());
            AssetDatabase.Refresh();
            Debug.Log($"[Neo.UI] Binding stub → {stub}\n          manifest → {manifestPath}");
            EditorUtility.DisplayDialog("Neo UI — Binding Stub",
                $"Stub written to:\n{stub}\n\nManifest:\n{manifestPath}\n\n" +
                "Implement the partial On…/Populate… hooks in your OWN sibling partial " +
                $"({ClassName(manifest)}.Handlers.cs) and call Wire() on startup.", "OK");
        }

        /// <summary> Writes the stub (creating folders + importing) and returns the asset path. </summary>
        public static string Write(BindingManifest manifest, string path, string namespaceName = DefaultNamespace)
        {
            if (string.IsNullOrEmpty(path)) path = DefaultPath(manifest);
            string directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);
            File.WriteAllText(path, Generate(manifest, namespaceName));
            if (path.Replace('\\', '/').StartsWith("Assets/")) AssetDatabase.ImportAsset(path);
            return path;
        }

        /// <summary> Pure, deterministic source generation — same manifest yields the same bytes. </summary>
        public static string Generate(BindingManifest manifest, string namespaceName = DefaultNamespace)
        {
            if (string.IsNullOrEmpty(namespaceName)) namespaceName = DefaultNamespace;
            string className = ClassName(manifest);
            var sb = new StringBuilder();
            var members = new HashSet<string>(); // dedup const/helper/handler names across the file

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated by Neo UI — Tools ▸ Neo UI ▸ Generate Binding Stub");
            sb.AppendLine("//     (or the `bindings` agent action). DO NOT EDIT — overwritten on regenerate.");
            sb.AppendLine($"//     Implement the partial On…/Populate… hooks in your OWN sibling partial file");
            sb.AppendLine($"//     (e.g. {className}.Handlers.cs in namespace {namespaceName}); that file is never touched.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Neo.UI;");
            sb.AppendLine("using Neo.UI.Menus;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>Wiring contract for the \"{Escape(manifest.flowName)}\" UI. Call <see cref=\"Wire\"/> once");
            sb.AppendLine("    /// after your views/menus have loaded (Start, not OnEnable — registries fill in OnEnable).</summary>");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");

            EmitViewConsts(sb, manifest, members);
            EmitSignalConsts(sb, manifest, members);
            EmitDataConsts(sb, manifest, members);
            EmitSettingConsts(sb, "Set", manifest.settings, members);
            EmitSettingConsts(sb, "Cheat", manifest.cheats, members);

            EmitWire(sb, manifest, members);
            EmitPopulateHelpers(sb, manifest, members);
            EmitHandlers(sb, manifest, members);

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ------------------------------------------------------------------ const sections

        private static void EmitViewConsts(StringBuilder sb, BindingManifest manifest, HashSet<string> members)
        {
            if (manifest.views.Count == 0) return;
            sb.AppendLine("        // ---- View ids ----");
            foreach (BindingManifest.ViewBinding view in manifest.views)
            {
                string member = Unique(members, "View" + Ident(view.category) + Ident(view.name));
                sb.AppendLine($"        public const string {member} = \"{Escape(view.id)}\";");
            }
            sb.AppendLine();
        }

        private static void EmitSignalConsts(StringBuilder sb, BindingManifest manifest, HashSet<string> members)
        {
            if (manifest.signals.Count == 0) return;
            sb.AppendLine("        // ---- Signal ids ----");
            foreach (BindingManifest.SignalBinding signal in manifest.signals)
            {
                string member = "Sig" + Ident(signal.category) + Ident(signal.name);
                if (!members.Add(member + "Category")) continue; // distinct stream already emitted
                members.Add(member + "Name");
                string note = signal.domain ? signal.payload : signal.payload + ", standard stream";
                sb.AppendLine($"        // {Escape(signal.source)} ({note})");
                sb.AppendLine($"        public const string {member}Category = \"{Escape(signal.category)}\";");
                sb.AppendLine($"        public const string {member}Name = \"{Escape(signal.name)}\";");
            }
            sb.AppendLine();
        }

        private static void EmitDataConsts(StringBuilder sb, BindingManifest manifest, HashSet<string> members)
        {
            if (manifest.dataSources.Count == 0) return;
            sb.AppendLine("        // ---- Data source ids ----");
            foreach (BindingManifest.DataSourceBinding source in manifest.dataSources)
            {
                CategorySplit(source.id, out string category, out string name);
                string member = "Data" + Ident(category) + Ident(name);
                if (!members.Add(member + "Category")) continue;
                members.Add(member + "Name");
                sb.AppendLine($"        // {Escape(source.source)} — tokens: {string.Join(", ", source.tokens)}");
                sb.AppendLine($"        public const string {member}Category = \"{Escape(category)}\";");
                sb.AppendLine($"        public const string {member}Name = \"{Escape(name)}\";");
            }
            sb.AppendLine();
        }

        private static void EmitSettingConsts(StringBuilder sb, string prefix,
            List<BindingManifest.SettingBinding> items, HashSet<string> members)
        {
            if (items.Count == 0) return;
            sb.AppendLine($"        // ---- {(prefix == "Cheat" ? "Cheat" : "Setting")} ids ----");
            foreach (BindingManifest.SettingBinding item in items)
            {
                string member = prefix + Ident(item.category) + Ident(item.name);
                if (!members.Add(member + "Category")) continue;
                members.Add(member + "Name");
                sb.AppendLine($"        // {item.kind} ({item.type})");
                sb.AppendLine($"        public const string {member}Category = \"{Escape(item.category)}\";");
                sb.AppendLine($"        public const string {member}Name = \"{Escape(item.name)}\";");
            }
            sb.AppendLine();
        }

        // ------------------------------------------------------------------ Wire()

        private static void EmitWire(StringBuilder sb, BindingManifest manifest, HashSet<string> members)
        {
            sb.AppendLine("        /// <summary>Subscribes every domain signal and binds every setting/cheat to a hook you");
            sb.AppendLine("        /// implement. Idempotent registration: call once (e.g. in Start).</summary>");
            sb.AppendLine("        public void Wire()");
            sb.AppendLine("        {");

            foreach (BindingManifest.SignalBinding signal in manifest.signals)
            {
                if (!signal.domain) continue; // standard firehose streams aren't auto-wired
                string member = "Sig" + Ident(signal.category) + Ident(signal.name);
                string handler = "On" + Ident(signal.category) + Ident(signal.name);
                if (signal.payload == "none")
                    sb.AppendLine($"            Signals.On({member}Category, {member}Name, () => {handler}());");
                else
                    sb.AppendLine($"            Signals.On<{signal.payload}>({member}Category, {member}Name, v => {handler}(v));");
            }

            EmitWireSettings(sb, "Set", manifest.settings);
            EmitWireSettings(sb, "Cheat", manifest.cheats);

            sb.AppendLine("        }");
            sb.AppendLine();
            EmitWireSettingHelper(sb, manifest);
        }

        private static void EmitWireSettings(StringBuilder sb, string prefix, List<BindingManifest.SettingBinding> items)
        {
            var seen = new HashSet<string>();
            foreach (BindingManifest.SettingBinding item in items)
            {
                if (item.type == "none") continue; // buttons/labels/rebinds carry no plain value to bind
                string member = prefix + Ident(item.category) + Ident(item.name);
                if (!seen.Add(member)) continue;
                string handler = "On" + Ident(item.category) + Ident(item.name) + "Changed";
                sb.AppendLine($"            BindSetting<{item.type}>({member}Category, {member}Name, v => {handler}(v));");
            }
        }

        private static void EmitWireSettingHelper(StringBuilder sb, BindingManifest manifest)
        {
            bool anySetting = HasBindable(manifest.settings) || HasBindable(manifest.cheats);
            if (!anySetting) return;
            sb.AppendLine("        // No silent failures (mirrors UIView.ProcessCommand): warn when an id matches no");
            sb.AppendLine("        // registered control — its catalog presenter hasn't loaded or the id is wrong.");
            sb.AppendLine("        private static void BindSetting<T>(string category, string name, Action<T> setter)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (UserSettingsService.GetDefinition(category, name) == null)");
            sb.AppendLine("                Debug.LogWarning($\"[Bindings] No settings/cheat control '{category}/{name}' is registered \" +");
            sb.AppendLine("                                 \"— bind it after the catalog presenter loads (Start), or fix the id.\");");
            sb.AppendLine("            UserSettingsService.Bind<T>(category, name, null, setter);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static bool HasBindable(List<BindingManifest.SettingBinding> items)
        {
            foreach (BindingManifest.SettingBinding item in items)
                if (item.type != "none") return true;
            return false;
        }

        // ------------------------------------------------------------------ Populate helpers

        private static void EmitPopulateHelpers(StringBuilder sb, BindingManifest manifest, HashSet<string> members)
        {
            if (manifest.dataSources.Count == 0) return;
            sb.AppendLine("        // ---- List population (string rows or your own type + a one-time projection) ----");
            var seen = new HashSet<string>();
            foreach (BindingManifest.DataSourceBinding source in manifest.dataSources)
            {
                CategorySplit(source.id, out string category, out string name);
                string ident = Ident(category) + Ident(name);
                if (!seen.Add(ident)) continue;
                string member = "Data" + ident;
                string tokens = source.tokens.Count > 0 ? string.Join(", ", source.tokens) : "(none)";
                sb.AppendLine($"        /// <summary>Fills the \"{Escape(source.id)}\" list. Row tokens: {tokens}.</summary>");
                sb.AppendLine($"        public void Populate{ident}(IEnumerable<IDictionary<string, string>> rows) =>");
                sb.AppendLine($"            UIData.Set({member}Category, {member}Name, rows);");
                sb.AppendLine();
                sb.AppendLine($"        /// <summary>Fills the \"{Escape(source.id)}\" list from your own type. Row tokens: {tokens}.</summary>");
                sb.AppendLine($"        public void Populate{ident}<T>(IEnumerable<T> rows, Func<T, IReadOnlyDictionary<string, string>> project) =>");
                sb.AppendLine($"            UIData.Set({member}Category, {member}Name, rows, project);");
                sb.AppendLine();
            }
        }

        // ------------------------------------------------------------------ partial hooks

        private static void EmitHandlers(StringBuilder sb, BindingManifest manifest, HashSet<string> members)
        {
            var handlers = new List<string>();
            var seen = new HashSet<string>();

            foreach (BindingManifest.SignalBinding signal in manifest.signals)
            {
                if (!signal.domain) continue;
                string handler = "On" + Ident(signal.category) + Ident(signal.name);
                string sig = signal.payload == "none" ? $"{handler}()" : $"{handler}({signal.payload} value)";
                if (seen.Add(handler)) handlers.Add($"        partial void {sig};");
            }
            AddSettingHandlers(handlers, seen, manifest.settings);
            AddSettingHandlers(handlers, seen, manifest.cheats);

            if (handlers.Count == 0) return;
            sb.AppendLine("        // ---- Implement these in your own partial (they are no-ops until you do) ----");
            foreach (string handler in handlers) sb.AppendLine(handler);
        }

        private static void AddSettingHandlers(List<string> handlers, HashSet<string> seen,
            List<BindingManifest.SettingBinding> items)
        {
            foreach (BindingManifest.SettingBinding item in items)
            {
                if (item.type == "none") continue;
                string handler = "On" + Ident(item.category) + Ident(item.name) + "Changed";
                if (seen.Add(handler)) handlers.Add($"        partial void {handler}({item.type} value);");
            }
        }

        // ------------------------------------------------------------------ helpers

        private static string Unique(HashSet<string> members, string candidate)
        {
            string name = candidate;
            int suffix = 2;
            while (!members.Add(name)) name = candidate + (suffix++);
            return name;
        }

        private static void CategorySplit(string id, out string category, out string name)
        {
            CategoryNameId.Parse(id, out category, out name);
        }

        /// <summary> A spec string → a safe Pascalish C# identifier fragment (preserves inner casing). </summary>
        private static string Ident(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            var sb = new StringBuilder(value.Length);
            bool upperNext = true;
            foreach (char c in value)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
                    upperNext = false;
                }
                else upperNext = true; // separators (/ space - etc.) start a new word
            }
            if (sb.Length == 0) return string.Empty;
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string Escape(string value) =>
            (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
